### ISSUE TITLE
Fairseq Installation Fails: Missing version.txt Error During Build Pyhton 3.11 how to fix?

### ISSUE THREAD

**Issue by brando90** [alycialee/beyond-scale-language-data-diversity#19]
https://stackoverflow.com/questions/78859329/fairseq-installation-fails-missing-version-txt-error-during-build-pyhton-3-11-h

```
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [19 lines of output]
    Traceback (most recent call last):
      File "/opt/conda/envs/beyond_scale_div_coeff/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
      File "/opt/conda/envs/beyond_scale_div_coeff/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/beyond_scale_div_coeff/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/pip-build-env-nrzuksph/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=[])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/tmp/pip-build-env-nrzuksph/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
        self.run_setup()
      File "/tmp/pip-build-env-nrzuksph/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
        exec(code, locals())
      File "<string>", line 27, in <module>
      File "<string>", line 18, in write_version_py
    FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by brando90** [comment]
https://chatgpt.com/c/bb70d4b7-b558-457e-8218-ab4a2a899d6f
